### ISSUE TITLE
educhat-sft-002-13b 解密(decrypt)失败

### ISSUE THREAD

**Issue by jnulzl** [ECNU-ICALK/EduChat#16]
如题，
 **Step1:将原始LLaMA权重转换为huggingface版本。** 成功，但是
**Step2:使用[解密脚本](https://github.com/icalk-nlp/EduChat/blob/main/decrypt.py)将增量权重加到原始LLaMA权重上。** 失败
错误如下所示：

```python
Traceback (most recent call last):
  File "../EduChat/decrypt.py", line 175, in <module>
    apply_delta(args.delta_path, args.target_model_path, args.base_model_path)
  File "../EduChat/decrypt.py", line 140, in apply_delta
    base = AutoModelForCausalLM.from_pretrained(
  File "/home/xxxxx/jnulzl/educhat_env/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/xxxxx/jnulzl/educhat_env/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3351, in from_pretrained
    resolved_archive_file, sharded_metadata = get_checkpoint_shard_files(
  File "/home/xxxxx/jnulzl/educhat_env/lib/python3.8/site-packages/transformers/utils/hub.py", line 994, in get_checkpoint_shard_files
    index = json.loads(f.read())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 138 column 19 (char 11002)
```

**python** 版本为:3.8.10
**transformers** 版本为:4.36.2

**Comment by butyuhao** [comment]
这个版本较老，建议您使用新版本的模型。
